name: clockin_clockout_flutter
description: clockin_clockout_flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  intl: ^0.19.0
  collection: ^1.15.0
  path_provider: ^2.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  flutter_animate: ^4.4.0
  excel: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: true
  image_path: "assets/app_logo.png"
  adaptive_icon_foreground: "assets/icon_foreground.png"
  adaptive_icon_background: "#383838"

flutter_native_splash:
  color: "#383838"
  image: assets/icon_foreground.png

flutter:
  uses-material-design: true